create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'admin');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null, full_name text not null default '', avatar_url text, bio text default '', role public.user_role not null default 'user', created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null, description text default '', created_at timestamptz not null default now());
create table public.articles (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles(id) on delete cascade, title text not null, slug text unique not null, excerpt text not null default '', content text not null default '', cover_image text, category_id uuid references public.categories(id) on delete set null, tags text[] not null default '{}', published boolean not null default false, reading_time integer not null default 1, likes_count integer not null default 0, bookmarks_count integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.comments (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, content text not null check (char_length(content) between 1 and 2000), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.likes (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), unique(article_id, user_id));
create table public.bookmarks (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), unique(article_id, user_id));

insert into public.categories (name, slug, description) values ('Technology','technology','Tools and ideas shaping tomorrow.'),('Programming','programming','Practical craft for building software.'),('AI','ai','The systems changing how we think and work.'),('Web Development','web-development','Modern interfaces and the web platform.'),('Business','business','Strategy, markets, and meaningful growth.'),('Education','education','Learning that compounds.'),('Gaming','gaming','Play, culture, and interactive worlds.'),('Lifestyle','lifestyle','A better way to spend your attention.'),('Productivity','productivity','Systems for doing work that matters.') on conflict (slug) do nothing;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, username, full_name, avatar_url) values (new.id, coalesce(nullif(new.raw_user_meta_data->>'username',''), 'user-' || substr(new.id::text,1,8)), coalesce(new.raw_user_meta_data->>'full_name',''), new.raw_user_meta_data->>'avatar_url'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.sync_like_count() returns trigger language plpgsql security definer as $$ begin update public.articles set likes_count = (select count(*) from public.likes where article_id = coalesce(new.article_id, old.article_id)) where id = coalesce(new.article_id, old.article_id); return coalesce(new, old); end; $$;
create trigger likes_count_insert after insert or delete on public.likes for each row execute procedure public.sync_like_count();
create or replace function public.sync_bookmark_count() returns trigger language plpgsql security definer as $$ begin update public.articles set bookmarks_count = (select count(*) from public.bookmarks where article_id = coalesce(new.article_id, old.article_id)) where id = coalesce(new.article_id, old.article_id); return coalesce(new, old); end; $$;
create trigger bookmarks_count_insert after insert or delete on public.bookmarks for each row execute procedure public.sync_bookmark_count();

alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.articles enable row level security; alter table public.comments enable row level security; alter table public.likes enable row level security; alter table public.bookmarks enable row level security;
create policy "public profiles" on public.profiles for select using (true); create policy "own profile update" on public.profiles for update using (auth.uid() = id); create policy "public categories" on public.categories for select using (true); create policy "published or owner articles" on public.articles for select using (published or auth.uid() = author_id or public.is_admin()); create policy "own article insert" on public.articles for insert with check (auth.uid() = author_id); create policy "own article update" on public.articles for update using (auth.uid() = author_id or public.is_admin()); create policy "own article delete" on public.articles for delete using (auth.uid() = author_id or public.is_admin()); create policy "public comments" on public.comments for select using (true); create policy "auth comments" on public.comments for insert with check (auth.uid() = user_id); create policy "own/admin comment delete" on public.comments for delete using (auth.uid() = user_id or public.is_admin()); create policy "public likes" on public.likes for select using (true); create policy "own likes" on public.likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "own bookmarks" on public.bookmarks for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "admin categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
insert into storage.buckets (id, name, public) values ('article-images','article-images',true) on conflict (id) do update set public = true;
create policy "public article images read" on storage.objects for select using (bucket_id = 'article-images'); create policy "users upload article images" on storage.objects for insert with check (bucket_id = 'article-images' and auth.uid()::text = (storage.foldername(name))[2]); create policy "users update article images" on storage.objects for update using (bucket_id = 'article-images' and auth.uid()::text = (storage.foldername(name))[2]); create policy "users delete article images" on storage.objects for delete using (bucket_id = 'article-images' and auth.uid()::text = (storage.foldername(name))[2]);
