import { useEffect, useState } from 'react'
import { ShieldCheck, Trash2, Users, FileText, MessageCircle, Layers } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { DashboardNav } from '../components/Layout'
export function AdminDashboard(){const [stats,setStats]=useState({});useEffect(()=>{Promise.all([supabase.from('profiles').select('id',{count:'exact',head:true}),supabase.from('articles').select('id',{count:'exact',head:true}),supabase.from('articles').select('id',{count:'exact',head:true}).eq('published',true),supabase.from('comments').select('id',{count:'exact',head:true}),supabase.from('categories').select('id',{count:'exact',head:true})]).then(([users,articles,published,comments,categories])=>setStats({users:users.count||0,articles:articles.count||0,published:published.count||0,comments:comments.count||0,categories:categories.count||0}))},[]);return <AdminLayout title="Admin overview"><div className="admin-badge"><ShieldCheck size={18}/> Admin control center</div><div className="stats-grid admin-stats"><AdminStat icon={<Users/>} label="Users" value={stats.users}/><AdminStat icon={<FileText/>} label="Articles" value={stats.articles}/><AdminStat icon={<Layers/>} label="Published" value={stats.published}/><AdminStat icon={<MessageCircle/>} label="Comments" value={stats.comments}/><AdminStat icon={<Layers/>} label="Categories" value={stats.categories}/></div><div className="workspace-empty admin-note"><h3>Moderation with context.</h3><p>Use the management views to keep Nexora useful, welcoming, and easy to navigate.</p></div></AdminLayout>}
function AdminStat({icon,label,value}){return <div className="stat-card"><span>{icon}</span><b>{value??'—'}</b><small>{label}</small></div>}
function AdminLayout({children,title}){return <main className="dashboard-page"><DashboardNav/><section className="dashboard-main"><div className="dash-heading"><div><span className="eyebrow">ADMINISTRATION</span><h1>{title}</h1></div></div>{children}</section></main>}
export function AdminArticles(){const [items,setItems]=useState([]);useEffect(()=>{supabase.from('articles').select('*, profiles:author_id(username,full_name), categories:category_id(name)').order('created_at',{ascending:false}).then(({data})=>setItems(data||[]))},[]);const remove=async id=>{if(!confirm('Delete this article?'))return;await supabase.from('articles').delete().eq('id',id);setItems(items.filter(x=>x.id!==id))};return <AdminLayout title="Manage articles"><div className="manage-list">{items.map(a=><div className="manage-row" key={a.id}><div><h3>{a.title}</h3><p>{a.profiles?.full_name||a.profiles?.username} · {a.published?'Published':'Draft'} · {a.categories?.name||'Uncategorized'}</p></div><div className="manage-actions"><button className="icon-danger" onClick={()=>remove(a.id)}><Trash2 size={16}/></button></div></div>)}</div></AdminLayout>}
export function AdminUsers(){const [items,setItems]=useState([]);useEffect(()=>{supabase.from('profiles').select('*').order('created_at',{ascending:false}).then(({data})=>setItems(data||[]))},[]);return <AdminLayout title="Manage users"><div className="manage-list">{items.map(u=><div className="manage-row" key={u.id}><span className="author-avatar">{(u.full_name||u.username).slice(0,1)}</span><div><h3>{u.full_name||u.username}</h3><p>@{u.username} · {u.role}</p></div></div>)}</div></AdminLayout>}
export function AdminComments(){const [items,setItems]=useState([]);const [error,setError]=useState('');useEffect(()=>{async function load(){const {data,error:commentsError}=await supabase.from('comments').select('*').order('created_at',{ascending:false});if(commentsError){setError(commentsError.message);return}const comments=data||[];const userIds=[...new Set(comments.map(comment=>comment.user_id))];const articleIds=[...new Set(comments.map(comment=>comment.article_id))];const [{data:profiles},{data:articles}]=await Promise.all([supabase.from('profiles').select('id,username,full_name').in('id',userIds),supabase.from('articles').select('id,title').in('id',articleIds)]);const profileMap=Object.fromEntries((profiles||[]).map(profile=>[profile.id,profile]));const articleMap=Object.fromEntries((articles||[]).map(article=>[article.id,article]));setItems(comments.map(comment=>({...comment,profiles:profileMap[comment.user_id],articles:articleMap[comment.article_id]})))}load()},[]);const remove=async id=>{const {error:deleteError}=await supabase.from('comments').delete().eq('id',id);if(deleteError){setError(deleteError.message);return}setItems(current=>current.filter(item=>item.id!==id))};return <AdminLayout title="Manage comments">{error&&<div className="alert error">{error}</div>}<div className="manage-list">{items.map(c=><div className="manage-row" key={c.id}><div><h3>{c.content}</h3><p>{c.profiles?.full_name||c.profiles?.username||'User'} on {c.articles?.title||'Article'}</p></div><button className="icon-danger" onClick={()=>remove(c.id)}><Trash2 size={16}/></button></div>)}</div></AdminLayout>}
export function AdminCategories(){const [items,setItems]=useState([]);const [name,setName]=useState('');useEffect(()=>{supabase.from('categories').select('*').order('name').then(({data})=>setItems(data||[]))},[]);const add=async e=>{e.preventDefault();if(!name.trim())return;const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-');const {data}=await supabase.from('categories').insert({name,slug}).select().single();if(data)setItems([...items,data]);setName('')};return <AdminLayout title="Manage categories"><form className="inline-form" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="New category name"/><button className="button">Add</button></form><div className="manage-list">{items.map(c=><div className="manage-row" key={c.id}><div><h3>{c.name}</h3><p>{c.description||c.slug}</p></div></div>)}</div></AdminLayout>}
